#!/bin/bash
#fmd db sync

maxsize=900000
baksize=1000000
FMD_PCx="/e/untied/FMD"
FMD_x230=""

# get where we are
if [ -d "$FMD_x230" ]; then
	# FMD="portable"
	encoderGit="/d/WorkSpace/=encoder="
	pathFMD="$FMD_x230"
	echo -e "\e[44mDirectory $FMD_x230 found. On the road mode...\e[0m"
elif [ -d "$FMD_PCx" ]; then
	# FMD="main"
	encoderGit="/d/_gitClone/[encoder]"
	pathFMD="$FMD_PCx"
	echo -e "\e[44mDirectory $FMD_PCx found. Homebase mode...\e[0m"
fi

# MAIN logic
if [ "$1" == 'pull' ]; then
	rsync -Ccazv --exclude='*.db-journal' "$encoderGit/manDB/works/" "$pathFMD/works/" --log-file="sync-fmd.$HOSTNAME:$1.log"
	cp "sync-fmd.$HOSTNAME:$1.log" "$(cygpath $USERPROFILE)/dotfiles/.logs/"
elif [ "$1" == 'push' ]; then
	# rsync -Ccazv "$pathFMD/data/" "$encoderGit/manDB/data/"
	rsync -Ccazv --exclude-from='.exclude-fmd' "$pathFMD/works/" "$encoderGit/manDB/works/" --log-file="sync-fmd.$HOSTNAME:$1.log"
	cp "sync-fmd.$HOSTNAME:$1.log" "$(cygpath $USERPROFILE)/dotfiles/.logs/"
else
	echo 'you have to specify pull or push'
fi

# log sizing & archiving
if [ -f "sync-fmd.$HOSTNAME:$1.log" ]; then
	filesize=$(stat -c%s "sync-fmd.$HOSTNAME:$1.log")
	if ((filesize > maxsize)) && ((filesize < baksize)); then
	    echo -e "\e[30;43mCaution: Log file is 900kb large. Consider backing up and/or deleting. Log will be automatically archived soon.\e[0m"
	elif ((filesize > baksize)); then
		echo -e "\e[34;43mAttention: Log file is 1mb large. Archiving...\e[0m"
		for i in {1..3}
		do
			if [ ! -f "sync-fmd.$HOSTNAME:$1.log.bak$i" ]; then
				tar -czvf "sync-fmd.$HOSTNAME:$1.log.bak$i" "sync-fmd.$HOSTNAME:$1.log" --remove-files
				echo -e "\e[34mLog file archived to sync-fmd.$HOSTNAME:$1.log.bak$i (uses tar gzip). Note that log backups are not sent to Git versioning.\e[0m"
				break
			elif [ -f "sync-fmd.$HOSTNAME:$1.log.bak1" ] && [ -f "sync-fmd.$HOSTNAME:$1.log.bak2" ] && [ -f "sync-fmd.$HOSTNAME:$1.log.bak3" ]; then
				echo -e "\e[31;44mArchive full! Highly advise deleting the log files and/or backups. This message will keep showing otherwise. File sync-fmd.$HOSTNAME:$1.log.bak$i exists.\e[0m"
			fi
		done
	fi
fi