#!/bin/bash
#fmd db sync

maxsize=900000
baksize=1000000
# paths - change these as needed
FMD_PCx="/e/untied/FMD"
FMD_x230="/c/untied/FMD"
encoder_PCx="/d/WorkSpace/=encoder="
encoder_x230="/d/_gitClone/[encoder]"

# get where we are
if [ -d "$FMD_x230" ]; then
	encoderGit="$encoder_x230"
	pathFMD="$FMD_x230"
	echo -e "\e[44mDirectory \e[33m$FMD_x230\e[37m found. Using \e[33m$encoder_x230\e[37m as Git versioning. \e[35mOn the road mode...\e[0m"
elif [ -d "$FMD_PCx" ]; then
	encoderGit="$encoder_PCx"
	pathFMD="$FMD_PCx"
	echo -e "\e[44mDirectory \e[33m$FMD_PCx\e[37m found. Using \e[33m$encoder_PCx\e[37m as Git versioning. \e[35mHomebase mode...\e[0m"
fi

# MAIN logic
if [ "$1" == 'pull' ]; then
	rsync -Ccazvvn --exclude-from='.exclude-fmd' "$encoderGit/manDB/works/" "$pathFMD/works/" | tee "sync-fmd.$HOSTNAME.${1^^}.DRY_RUN" | GREP_COLORS='mt=1;93' egrep --color=always '(total:).*|(sending incremental file list)|(delta-transmission).*|.*(bytes\/sec)|.*(\(DRY RUN\))|$' | GREP_COLORS='mt=1;34' egrep --color=always '^(\[sender\]).*|$' | GREP_COLORS='mt=1;31' egrep --color=always '(deleting).*|$' | GREP_COLORS='mt=1;32' egrep --color=always '.*(uptodate)$|$' | less -R
	read -p "Confirm $1? [no] " yesOrYes
	yesOrYes=${yesOrYes:-no}
	if [ "$yesOrYes" == 'yes' ]; then
		rsync -Ccazv --exclude-from='.exclude-fmd' "$encoderGit/manDB/works/" "$pathFMD/works/" --log-file="sync-fmd.$HOSTNAME.${1^^}.log"
		cp "sync-fmd.$HOSTNAME.${1^^}.log" "$(cygpath $USERPROFILE)/dotfiles/.logs/"
		rm "sync-fmd.$HOSTNAME.${1^^}.DRY_RUN"
	fi
elif [ "$1" == 'push' ]; then
	# rsync -Ccazv "$pathFMD/data/" "$encoderGit/manDB/data/"
	rsync -Ccazvvn --exclude-from='.exclude-fmd' "$pathFMD/works/" "$encoderGit/manDB/works/" | tee "sync-fmd.$HOSTNAME.${1^^}.DRY_RUN" | GREP_COLORS='mt=1;93' egrep --color=always '(total:).*|(sending incremental file list)|(delta-transmission).*|.*(bytes\/sec)|.*(\(DRY RUN\))|$' | GREP_COLORS='mt=1;34' egrep --color=always '^(\[sender\]).*|$' | GREP_COLORS='mt=1;31' egrep --color=always '(deleting).*|$' | GREP_COLORS='mt=1;32' egrep --color=always '.*(uptodate)$|$' | less -R
	read -p "Confirm $1? [no] " yesOrYes
	yesOrYes=${yesOrYes:-no}
	if [ "$yesOrYes" == 'yes' ]; then
		rsync -Ccazv --exclude-from='.exclude-fmd' "$pathFMD/works/" "$encoderGit/manDB/works/" --log-file="sync-fmd.$HOSTNAME.${1^^}.log"
		cp "sync-fmd.$HOSTNAME.${1^^}.log" "$(cygpath $USERPROFILE)/dotfiles/.logs/"
		rm "sync-fmd.$HOSTNAME.${1^^}.DRY_RUN"
	fi
else
	echo 'you have to specify pull or push'
fi

# log sizing & archiving
if [ -f "sync-fmd.$HOSTNAME.${1^^}.log" ]; then
	filesize=$(stat -c%s "sync-fmd.$HOSTNAME.${1^^}.log")
	if ((filesize > maxsize)) && ((filesize < baksize)); then
	    echo -e "\e[30;43mCaution: Log file is 900kb large. Consider backing up and/or deleting. Log will be automatically archived soon.\e[0m"
	elif ((filesize > baksize)); then
		echo -e "\e[34;43mAttention: Log file is 1mb large. Archiving...\e[0m"
		for i in {1..3}
		do
			if [ ! -f "sync-fmd.$HOSTNAME.${1^^}.log.bak$i" ]; then
				tar -czvf "sync-fmd.$HOSTNAME.${1^^}.log.bak$i" "sync-fmd.$HOSTNAME.${1^^}.log" --remove-files
				echo -e "\e[34mLog file archived to sync-fmd.$HOSTNAME.${1^^}.log.bak$i (uses tar gzip). Note that log backups are not sent to Git versioning.\e[0m"
				break
			elif [ -f "sync-fmd.$HOSTNAME.${1^^}.log.bak1" ] && [ -f "sync-fmd.$HOSTNAME.${1^^}.log.bak2" ] && [ -f "sync-fmd.$HOSTNAME.${1^^}.log.bak3" ]; then
				echo -e "\e[31;44mArchive full! Highly advise deleting the log files and/or backups. This message will keep showing otherwise. File sync-fmd.$HOSTNAME.${1^^}.log.bak$i exists.\e[0m"
			fi
		done
	fi
fi