#!/bin/bash
#sync scoop persistence

#TODO:Test portable

maxsize=900000
baksize=1000000

# get where we are
if [ -d "$scoop_x230" ]; then
	scoop="portable"
	echo -e "\e[44mDirectory $scoop_x230 found. On the road mode...\e[0m"
elif [ -d "$scoop_PCx" ]; then
	scoop="main"
	echo -e "\e[44mDirectory $scoop_PCx found. Homebase mode...\e[0m"
fi

# MAIN logic
if [ "$1" == 'pull' ]; then
	rsync -Ccazv "$(cygpath $USERPROFILE)/dotfiles/win10_userprofile/scoop_persist/" "$(cygpath $USERPROFILE)/.scoopy/persist/" --log-file="sync-persist.$HOSTNAME:$1.log"
	cp "sync-persist.$HOSTNAME:$1.log" "$(cygpath $USERPROFILE)/dotfiles/.logs/"
elif [ "$1" == 'push' ]; then
	rsync -Ccazv --exclude-from=".exclude-persist" "$(cygpath $USERPROFILE)/.scoopy/persist/" "$(cygpath $USERPROFILE)/dotfiles/win10_userprofile/scoop_persist/" --log-file="sync-persist.$HOSTNAME:$1.log"
	cp "sync-persist.$HOSTNAME:$1.log" "$(cygpath $USERPROFILE)/dotfiles/.logs/"
else
	echo 'you have to specify pull or push'
fi

# log sizing & archiving
if [ -f "sync-persist.$HOSTNAME:$1.log" ]; then
	filesize=$(stat -c%s "sync-persist.$HOSTNAME:$1.log")
	if ((filesize > maxsize)) && ((filesize < baksize)); then
	    echo -e "\e[30;43mCaution: Log file is 900kb large. Consider backing up and/or deleting. Log will be automatically archived soon.\e[0m"
	elif ((filesize > baksize)); then
		echo -e "\e[34;43mAttention: Log file is 1mb large. Archiving...\e[0m"
		for i in {1..3}
		do
			if [ ! -f "sync-persist.$HOSTNAME:$1.log.bak$i" ]; then
				tar -czvf "sync-persist.$HOSTNAME:$1.log.bak$i" "sync-persist.$HOSTNAME:$1.log" --remove-files
				echo -e "\e[34mLog file archived to sync-persist.$HOSTNAME:$1.log.bak$i (uses tar gzip). Note that log backups are not sent to Git versioning.\e[0m"
				break
			elif [ -f "sync-persist.$HOSTNAME:$1.log.bak1" ] && [ -f "sync-persist.$HOSTNAME:$1.log.bak2" ] && [ -f "sync-persist.$HOSTNAME:$1.log.bak3" ]; then
				echo -e "\e[31;44mArchive full! Highly advise deleting the log files and/or backups. This message will keep showing otherwise. File sync-persist.$HOSTNAME:$1.log.bak$i exists.\e[0m"
			fi
		done
	fi
fi