#!/usr/bin/env bash
#profile config sync

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# log file size
maxsize=900000
baksize=1000000
# paths
pwshProfile="$(cygpath $USERPROFILE)/Documents/PowerShell"
powershellProfile="$(cygpath $USERPROFILE)/Documents/WindowsPowerShell"
terminalProfile="$(cygpath $LOCALAPPDATA)/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
dotfiles="$(cygpath $USERPROFILE)/dotfiles"
dotfilesDirPWSH="win10_userprofile/powershell"
dotfilesDirTERM="win10_userprofile/win_terminal"
dotfilesDirMSYS="msys2_mainHome"
# preview coloring
grepSysCol="mt=1;93;44"
grepSendCol="mt=1;34"
grepSkipCol="mt=1;35"
grepDelCol="mt=1;31"
grepUnchCol="mt=1;32"
grepSysMsg='(total:).*|(sending incremental file list)|(delta-transmission).*|.*(bytes\/sec)|.*(\(DRY RUN\))|$'
grepSendMsg='^(\[sender\]).*|$'
grepSkipMsg='(not creating new file).*|$'
grepDelMsg='(deleting).*|$'
grepUnchMsg='.*(uptodate)$|$'
# logfiles
runLog="$(basename $0).$HOSTNAME.log"
dryLog="$(basename $0).$HOSTNAME.DRY_RUN"
# excludes/filter files
filterFile="$DIR/.filter-profile"

# test filters (if needed)
if [ ! -z ${filterFile+x} ]; then
	if [ ! -f $filterFile ]; then
		echo -e "\e[31mFile $filterFile not found!\e[0m"
		exit 1
	fi
fi

function usage() {
	cat <<HELP_USAGE

    usage: $(basename $0) [ps|pl] [pwsh|term|msys]

    -h, --help			Print this message
    ps, push			Sync current directory to git repo
    pl, pull			Sync git repo to current dir

    pwsh, powershell		Sync Windows Powershell (v5.1) and Powershell Core (v6.4++) profile
    term, terminal, winterminal	Sync Windows Terminal profile
    msys, msys2, bash		Sync MSYS2 home profile
HELP_USAGE

	exit 0
}

function path_input() {
	read -e -p "Please enter path to profile: " source
	if [ ! -f "$source/$2" ]; then
		echo -e "\e[30;43mWARNING: file $source/$2 not found (wrong sync dir?), exiting...\e[0m"
		exit 1
	fi
}

function define_source() {
	if [ ! -d "$dotfiles" ]; then
		echo -e "\e[30;43mWARNING: $dotfiles not found, exiting...\e[0m"
		exit 1
	fi
	if [ -d "$1" ]; then
		source="$1"
		read -p $'\e[44mProfile found on \e[33m'"$source"$'\e[0m\n' -t 5
	else
		echo -e "\e[31mProfile directory not found. Is it installed?\e[0m"
		path_input $2
	fi
}

function main_logic() {
	# TODO change rsync compare to use diff since this is a one file
	# DIFF=$(diff a b)
	# if [ "$DIFF" != "" ]; then
	# 	echo "The directory was modified"
	# fi
	rsync -Ccazvvn --existing --filter="merge $filterFile" "$1" "$2" | tee "$HOME/.logs/$dryLog" | GREP_COLORS="$grepSysCol" egrep --color=always "$grepSysMsg" | GREP_COLORS="$grepSendCol" egrep --color=always "$grepSendMsg" | GREP_COLORS="$grepSkipCol" egrep --color=always "$grepSkipMsg" | GREP_COLORS="$grepDelCol" egrep --color=always "$grepDelMsg" | GREP_COLORS="$grepUnchCol" egrep --color=always "$grepUnchMsg" | less -R
	read -p "Confirm $sync? [no] " yesOrYes
	yesOrYes=${yesOrYes:-no}
	if [ "$yesOrYes" == 'yes' ] || [ "$yesOrYes" == 'y' ]; then
		echo "$1 $sync to $2" >>$HOME/.logs/$runLog
		rsync -Ccaziiv --existing --filter="merge $filterFile" "$1" "$2" --log-file="$HOME/.logs/$runLog" && rm "$HOME/.logs/$dryLog"
		if [ -f "$dotfiles/.logs/$runLog" ] && [ -f "$HOME/.logs/$runLog" ]; then
			diff -u $dotfiles/.logs/$runLog $HOME/.logs/$runLog | grep -E "^\+" | sed -E 's/^\+//' >>$dotfiles/.logs/$runLog
			cp "$dotfiles/.logs/$runLog" "$HOME/.logs/"
		else
			cp "$HOME/.logs/$runLog" "$dotfiles/.logs/"
		fi
	fi
}

function command_param() {
	case $1 in

	pl | pull)
		sync="pull"
		;;

	ps | push)
		sync="push"
		;;

	"" | -h | --help)
		usage
		;;

	*)
		echo "Unknown option - $1"
		usage
		;;
	esac

	case $2 in

	pwsh | powershell)
		define_source "$pwshProfile" "profile.ps1"
		echo -e "\e[44m${sync[@]^}ing Powershell Core profile\e[0m"
		if [ "$sync" == "pull" ]; then
			main_logic "$dotfiles/$dotfilesDirPWSH/" "$source/"
			define_source "$powershellProfile" "profile.ps1"
			echo -e "\e[44m${sync[@]^}ing Powershell profile\e[0m"
			main_logic "$dotfiles/$dotfilesDirPWSH/" "$source/"
		elif [ "$sync" == "push" ]; then
			main_logic "$source/" "$dotfiles/$dotfilesDirPWSH/"
			echo -e "\e[43mNot pushing Windows Powershell profile (this should follow pwsh)\e[0m"
		fi
		;;

	term | terminal | winterminal)
		define_source "$terminalProfile" "profiles.json"
		echo -e "\e[44m${sync[@]^}""ing terminal profile\e[0m"
		if [ "$sync" == "pull" ]; then
			main_logic "$dotfiles/$dotfilesDirTERM/" "$source/"
		elif [ "$sync" == "push" ]; then
			main_logic "$source/" "$dotfiles/$dotfilesDirTERM/"
		fi
		;;

	msys | msys2 | bash)
		define_source "$HOME" ".bash_profile"
		echo -e "\e[44m${sync[@]^}""ing MSYS2 profile\e[0m"
		if [ "$sync" == "pull" ]; then
			main_logic "$dotfiles/$dotfilesDirMSYS/" "$HOME/"
		elif [ "$sync" == "push" ]; then
			main_logic "$HOME/" "$dotfiles/$dotfilesDirMSYS/"
		fi
		;;

	"")
		echo "You have to specify profile to sync"
		usage
		;;

	*)
		echo "Unknown profile - $2"
		usage
		;;
	esac
}

if [ $# -gt 2 ]; then
	for ((i = 3; i <= $#; i++)); do
		echo "No parameter ${!i} found"
	done
	usage
else
	command_param $1 $2
fi

# log archiving
if [ -f "$HOME/.logs/$runLog" ]; then
	filesize=$(stat -c%s "$HOME/.logs/$runLog")
	if ((filesize > maxsize)) && ((filesize < baksize)); then
		echo -e "\e[30;43mCaution: Log file is 900kb large. Consider backing up and/or deleting. Log will be automatically archived soon.\e[0m"
	elif ((filesize > baksize)); then
		echo -e "\e[34;43mAttention: Log file is 1mb large. Archiving...\e[0m"
		for i in {1..3}; do
			if [ ! -f "$HOME/.logs/$runLog.bak$i" ]; then
				tar -czvf "$HOME/.logs/$runLog.bak$i" "$HOME/.logs/$runLog" --remove-files
				echo -e "\e[34mLog file archived to $HOME/.logs/$runLog.bak$i (uses tar gzip). Note that log backups are not sent to Git versioning.\e[0m"
				break
			elif [ -f "$HOME/.logs/$runLog.bak1" ] && [ -f "$HOME/.logs/$runLog.bak2" ] && [ -f "$HOME/.logs/$runLog.bak3" ]; then
				echo -e "\e[31;44mArchive full! Highly advise deleting the log files and/or backups. This message will keep showing otherwise. File $HOME/.logs/$runLog.bak$i exists.\e[0m"
			fi
		done
	fi
fi
